# Generated by Django 5.2.4 on 2025-07-05 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('planifie', models.BooleanField(default=False)),
                ('justification', models.TextField(blank=True)),
                ('effectif', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carte.lieu')),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('positions', models.ManyToManyField(related_name='unites', to='carte.position')),
            ],
        ),
    ]
