# Generated by Django 5.2.4 on 2025-07-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
