# Generated by Django 5.2.4 on 2025-07-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0002_alter_lieu_latitude_alter_lieu_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='effectif',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
