# Generated by Django 5.2.4 on 2025-08-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0003_alter_position_effectif_alter_position_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='lieu_str',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
