# Generated by Django 5.2.4 on 2025-08-06 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0004_position_lieu_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='camp',
            field=models.CharField(choices=[('COALISES', 'Coalisés'), ('FRANCAIS', 'Français'), ('NONE', 'None')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='unite',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dirige', to='carte.unite')),
                ('unite_commandee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='est_dirigee_par', to='carte.unite')),
            ],
        ),
        migrations.CreateModel(
            name='Subordonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('unite_commandant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_a', to='carte.unite')),
                ('unite_subordonnee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordonnee_a', to='carte.unite')),
            ],
        ),
    ]
