# Generated by Django 5.2.4 on 2025-08-06 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0005_unite_camp_unite_grade_commande_subordonne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carte.lieu'),
        ),
    ]
