# Generated by Django 5.2.4 on 2025-08-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0006_alter_position_lieu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lieu_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lieu_arrivee_arrow', to='carte.lieu')),
                ('lieu_depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lieu_depart_arrow', to='carte.lieu')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unite_arrow', to='carte.unite')),
            ],
        ),
    ]
