# Generated by Django 5.2.4 on 2025-09-02 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0007_arrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('lieu_str', models.CharField(blank=True, max_length=300, null=True)),
                ('date', models.DateField()),
                ('lieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carte.lieu')),
            ],
        ),
        migrations.DeleteModel(
            name='Arrow',
        ),
    ]
