# Generated by Django 5.2.4 on 2025-09-07 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0008_combat_delete_arrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='unite',
            name='echelon',
            field=models.CharField(choices=[('armée', 'Armée'), ('corps', 'Corps'), ('division', 'Division'), ('brigade', 'Brigade'), ('régiment', 'Régiment'), ('bataillon', 'Bataillon'), ('escadron', 'Escadron'), ('inconnu', 'Inconnu')], default='inconnu', max_length=10),
        ),
        migrations.AlterField(
            model_name='combat',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lieu_combat', to='carte.lieu'),
        ),
        migrations.AlterField(
            model_name='position',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='carte.lieu'),
        ),
    ]
