# Generated by Django 5.2.4 on 2025-09-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0009_unite_echelon_alter_combat_lieu_alter_position_lieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unite',
            name='echelon',
            field=models.CharField(choices=[('armee', 'Armée'), ('corps', 'Corps'), ('division', 'Division'), ('brigade', 'Brigade'), ('regiment', 'Régiment'), ('bataillon', 'Bataillon'), ('escadron', 'Escadron'), ('inconnu', 'Inconnu')], default='inconnu', max_length=10),
        ),
    ]
