# Generated by Django 5.2.4 on 2025-10-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0010_alter_unite_echelon'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='date_approx',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='date_approx',
            field=models.BooleanField(default=False),
        ),
    ]
