# Generated by Django 5.2.4 on 2025-10-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0011_combat_date_approx_position_date_approx'),
    ]

    operations = [
        migrations.AddField(
            model_name='combat',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combat',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
