# Generated by Django 5.2.4 on 2025-12-29 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0012_combat_justification_combat_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lettre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('contenu', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('destinataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinataire', to='carte.unite')),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expediteur', to='carte.unite')),
                ('lieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carte.lieu')),
            ],
        ),
    ]
