# Generated by Django 5.2.4 on 2025-12-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0013_lettre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettre',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
